import { DashboardNav } from "@/components/Dashboard/index";
import PortfolioNav from "@/components/Portfolio/PortfolioNav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CareerMate | User Portfolio",
  description:
    " User Portfolio generated by CareerMate ",
  icons: {
    icon: "/logo.png",
  },
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <PortfolioNav />
      <main>{children}</main>
    </section>
  );
}
